apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: prover-combined-stress
  description: Combined CPU and memory stress on prover to test proof generation resilience
  tags:
  - resource
  - cpu
  - memory
  - high
  - prover
  - zk
  author: DevTools
  version: 0.0.1
spec:
  targets:
  - selector:
      type: kurtosis_service
      enclave: ${ENCLAVE_NAME}
      pattern: .*prover.*|zkevm-prover.*|op-succinct-proposer.*
    alias: prover_node
  duration: 10m
  warmup: 2m
  cooldown: 2m
  faults:
  - phase: cpu_stress_prover
    description: Stress prover CPU at 60% on 3 cores
    target: prover_node
    type: cpu_stress
    params:
      cpu_percent: 60
      cores: 3
      method: stress
  - phase: memory_stress_prover
    description: Apply memory pressure consuming 1.5GB
    target: prover_node
    type: memory_pressure
    params:
      memory_mb: 1536
  success_criteria:
  - name: proofs_eventually_generated
    description: Proofs are eventually generated (may be delayed)
    type: prometheus
    query: increase(panoptichain_rpc_height[10m])
    threshold: '> 0'
    window: 10m
    critical: false
  - name: proof_generation_delayed_but_completes
    description: Proof generation times increase but proofs complete
    type: prometheus
    query: rate(panoptichain_rpc_block_interval_sum[3m]) / clamp_min(rate(panoptichain_rpc_block_interval_count[3m]),
      0.001)
    threshold: < 900
    window: 10m
    critical: false
  metrics:
  - panoptichain_rpc_height
  - panoptichain_rpc_block_interval_sum
  - panoptichain_rpc_gas_used_sum
  - process_cpu_seconds_total
  - process_resident_memory_bytes
  - up
