apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: op-proposer-memory-leak
  description: Simulate memory exhaustion on OP proposer to test output proposal resilience
  tags:
  - resource
  - memory
  - critical
  - op-stack
  - proposer
  author: DevTools
  version: 0.0.1
spec:
  targets:
  - selector:
      type: kurtosis_service
      enclave: ${ENCLAVE_NAME}
      pattern: op-proposer.*
    alias: op_proposer
  duration: 6m
  warmup: 1m
  cooldown: 1m
  faults:
  - phase: memory_leak_proposer
    description: Apply progressive memory pressure on proposer
    target: op_proposer
    type: memory_pressure
    params:
      memory_mb: 1024
  success_criteria:
  - name: output_proposals_continue
    description: Output proposals continue being submitted
    type: prometheus
    query: increase(panoptichain_rpc_height[3m])
    threshold: '> 0'
    window: 6m
    critical: false
  - name: transaction_throughput_maintained
    description: Transaction processing rate doesn't drop significantly
    type: prometheus
    query: rate(panoptichain_rpc_gas_used_count[1m])
    threshold: '> 0.1'
    window: 5m
    critical: false
  - name: empty_blocks_low
    description: Not producing too many empty blocks
    type: prometheus
    query: rate(panoptichain_rpc_empty_block[2m])
    threshold: < 0.5
    window: 5m
    critical: false
  - name: block_time_stable
    description: Block time remains stable despite resource pressure
    type: prometheus
    query: rate(panoptichain_rpc_block_interval_sum[2m]) / rate(panoptichain_rpc_block_interval_count[2m])
    threshold: < 5.0
    window: 5m
    critical: false
  - name: sequencer_unaffected
    description: Sequencer continues producing blocks
    type: prometheus
    query: increase(panoptichain_rpc_height{job=~"op-el-1.*"}[1m])
    threshold: '> 0'
    window: 6m
    critical: true
  metrics:
  - process_resident_memory_bytes
  - panoptichain_rpc_height
  - up
  - panoptichain_rpc_gas_used_count
  - panoptichain_rpc_empty_block
  - panoptichain_rpc_block_interval_sum
  - panoptichain_rpc_block_interval_count
  - panoptichain_rpc_transactions_per_block_sum
  - panoptichain_rpc_transactions_per_block_count
  - panoptichain_rpc_time_to_mine_sum
  - panoptichain_rpc_time_to_mine_count
