apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: cross-stack-partition
  description: Partition L1 from all L2 services to test complete L1 isolation
  tags:
  - network
  - partition
  - critical
  - l1
  - multi-target
  author: DevTools
  version: 0.0.1
spec:
  targets:
  - selector:
      type: kurtosis_service
      enclave: ${ENCLAVE_NAME}
      pattern: el-1-geth.*
    alias: l1_execution
  - selector:
      type: kurtosis_service
      enclave: ${ENCLAVE_NAME}
      pattern: cl-1-lighthouse.*
    alias: l1_consensus
  duration: 5m
  warmup: 30s
  cooldown: 30s
  faults:
  - phase: partition_l1_execution
    description: Isolate L1 execution layer from network
    target: l1_execution
    type: network
    params:
      device: eth0
      packet_loss: 100
      target_proto: tcp,udp
  - phase: partition_l1_consensus
    description: Isolate L1 consensus layer from network
    target: l1_consensus
    type: network
    params:
      device: eth0
      packet_loss: 100
      target_proto: tcp,udp
  success_criteria:
  - name: l2_continues_producing_blocks
    description: L2 continues producing blocks despite L1 isolation (for duration
      of test)
    type: prometheus
    query: increase(panoptichain_rpc_height{job=~".*sequencer.*|.*l2.*"}[1m])
    threshold: '> 0'
    window: 5m
    critical: true
  - name: batch_submissions_fail
    description: Batch submissions to L1 fail during partition
    type: prometheus
    query: increase(panoptichain_rpc_height[3m])
    threshold: == 0
    window: 3m
    critical: false
  metrics:
  - panoptichain_rpc_height
  - panoptichain_rpc_gas_used_sum
  - up
