apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: postgres-connection-latency
  description: Inject 200ms latency on PostgreSQL connections to test database resilience
  tags:
  - network
  - latency
  - medium
  - database
  - postgres
  author: DevTools
  version: 0.0.1
spec:
  targets:
  - selector:
      type: kurtosis_service
      enclave: ${ENCLAVE_NAME}
      pattern: postgres.*
    alias: postgres_db
  duration: 5m
  warmup: 30s
  cooldown: 30s
  faults:
  - phase: postgres_latency
    description: Add 200ms latency to PostgreSQL connections
    target: postgres_db
    type: network
    params:
      device: eth0
      latency: 200
      target_ports: '5432'
      target_proto: tcp
  success_criteria:
  - name: services_continue_operating
    description: Services continue operating despite slow database
    type: prometheus
    query: increase(panoptichain_rpc_height[1m])
    threshold: '> 0'
    window: 5m
    critical: true
  - name: block_time_stable
    description: Block time remains stable (not increasing significantly)
    type: prometheus
    query: rate(panoptichain_rpc_block_interval_sum[2m]) / rate(panoptichain_rpc_block_interval_count[2m])
    threshold: < 5.0
    window: 5m
    critical: false
  - name: transaction_throughput_maintained
    description: Transaction processing rate doesn't drop significantly
    type: prometheus
    query: rate(panoptichain_rpc_gas_used_count[1m])
    threshold: '> 0.1'
    window: 5m
    critical: false
  - name: services_maintain_functionality
    description: Services maintain functionality despite database latency
    type: prometheus
    query: increase(panoptichain_rpc_gas_used_sum[2m])
    threshold: '> 0'
    window: 5m
    critical: false
  - name: proofs_being_generated
    description: ZK proofs are being generated
    type: prometheus
    query: increase(succinct_highest_proven_contiguous_block[10m])
    threshold: '> 0'
    window: 10m
    critical: false
  - name: l2_finalization_continues
    description: L2 blocks continue to be finalized with ZK proofs
    type: prometheus
    query: increase(succinct_l2_finalized_block[10m])
    threshold: '> 0'
    window: 10m
    critical: false
  metrics:
  - panoptichain_rpc_height
  - panoptichain_rpc_gas_used_sum
  - up
  - panoptichain_rpc_block_interval_sum
  - panoptichain_rpc_block_interval_count
  - panoptichain_rpc_gas_used_count
  - panoptichain_rpc_finalized_height
  - panoptichain_rpc_time_to_finalized
  - panoptichain_rpc_time_to_mine_sum
  - panoptichain_rpc_time_to_mine_count
  - succinct_l2_finalized_block
  - succinct_highest_proven_contiguous_block
  - succinct_current_proving_proofs
  - succinct_agg_proof_request_error_count
