apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: prover-high-latency
  description: Inject 800ms latency on prover communication to test proof generation delays
  tags: [network, latency, high, prover, zk]
  author: DevTools
  version: "0.0.1"

spec:
  # Target prover service (multiple patterns for different stacks)
  targets:
    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: ".*prover.*|zkevm-prover.*|op-succinct-proposer.*"
      alias: prover_node

  duration: 8m
  warmup: 1m
  cooldown: 1m

  # Add 800ms latency on prover communication
  faults:
    - phase: prover_latency
      description: Add 800ms latency to prover network communication
      target: prover_node
      type: network
      params:
        device: eth0
        latency: 800
        target_proto: tcp,udp

  success_criteria:
    - name: sequencer_unaffected
      description: Sequencer continues producing blocks despite slow prover
      type: prometheus
      query: increase(panoptichain_rpc_height{job=~".*sequencer.*"}[1m])
      threshold: "> 0"
      window: 8m
      critical: true

    - name: proofs_eventually_generated
      description: Proofs are eventually generated despite latency
      type: prometheus
      query: increase(panoptichain_rpc_height[8m])
      threshold: "> 0"
      window: 8m
      critical: false

    - name: proof_generation_delayed
      description: Proof generation times increase but complete
      type: prometheus
      query: rate(panoptichain_rpc_block_interval_sum[2m]) / clamp_min(rate(panoptichain_rpc_block_interval_count[2m]), 0.001)
      threshold: "< 600"
      window: 8m
      critical: false

  metrics:
    - panoptichain_rpc_height
    - panoptichain_rpc_block_interval_sum
    - panoptichain_rpc_gas_used_sum
    - up
