apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: bandwidth-throttle-validator
  description: Throttle network bandwidth for a validator to simulate congested network
  tags: [network, bandwidth, performance, medium-severity]
  author: DevTools
  version: "0.0.1"

spec:
  targets:
    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-cl-1-heimdall-v2-bor-validator"
      alias: throttled_validator

  duration: 6m
  warmup: 30s
  cooldown: 30s

  faults:
    - phase: bandwidth_limit
      description: Limit bandwidth to 1 Mbps to simulate congested network
      target: throttled_validator
      type: network
      params:
        device: eth0
        bandwidth: 1000  # 1 Mbps in kbps
        target_proto: tcp,udp

  success_criteria:
    # Critical: Block production must continue
    - name: block_production_continues
      description: Network continues producing blocks
      type: prometheus
      query: increase(chain_head_block{job=~"l2-el-.*-bor-heimdall-v2-validator"}[1m])
      threshold: "> 0"
      window: 6m
      critical: true

    # Critical: Consensus continues
    - name: consensus_continues
      description: Consensus layer continues operating
      type: prometheus
      query: increase(cometbft_consensus_height{job=~"l2-cl-.*-heimdall-v2-bor-validator"}[1m])
      threshold: "> 0"
      window: 6m
      critical: true

    # Non-critical: Checkpoint API accessible
    - name: checkpoint_api_accessible
      description: Checkpoint API continues to respond
      type: prometheus
      query: increase(heimdallv2_checkpoint_api_calls_total[2m])
      threshold: ">= 0"
      window: 6m
      critical: false

  metrics:
    - chain_head_block
    - cometbft_consensus_height
    - heimdallv2_checkpoint_api_calls_total
