apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: cpu-starved-validator
  description: Validator with CPU throttling - simulates CPU-starved environment or noisy neighbor
  tags: [cpu, resource-exhaustion, performance, medium-severity]
  author: DevTools
  version: "0.0.1"

spec:
  targets:
    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-cl-3-heimdall-v2-bor-validator"
      alias: cpu_throttled_heimdall

    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-el-3-bor-heimdall-v2-validator"
      alias: cpu_throttled_bor

  duration: 8m
  warmup: 2m
  cooldown: 2m

  # Progressive CPU throttling
  faults:
    # Phase 1: 80% CPU stress (high load)
    - phase: moderate_cpu_throttle_heimdall
      description: Stress Heimdall CPU at 80% on 2 cores
      target: cpu_throttled_heimdall
      type: cpu_stress
      params:
        cpu_percent: 80
        cores: 2
        method: stress  # Active CPU stress - will spike CPU usage!
      duration: 4m

    - phase: moderate_cpu_throttle_bor
      description: Stress Bor CPU at 80% on 2 cores
      target: cpu_throttled_bor
      type: cpu_stress
      params:
        cpu_percent: 80
        cores: 2
        method: stress  # Active CPU stress - will spike CPU usage!
      duration: 4m

    # Phase 2: 95% CPU stress (extreme load)
    - phase: severe_cpu_throttle_heimdall
      description: Stress Heimdall CPU at 95% on 3 cores (extreme load)
      target: cpu_throttled_heimdall
      type: cpu_stress
      params:
        cpu_percent: 95
        cores: 3
        method: stress  # Active CPU stress - extreme load!
      duration: 4m
      delay: 4m

    - phase: severe_cpu_throttle_bor
      description: Stress Bor CPU at 95% on 3 cores (extreme load)
      target: cpu_throttled_bor
      type: cpu_stress
      params:
        cpu_percent: 95
        cores: 3
        method: stress  # Active CPU stress - extreme load!
      duration: 4m
      delay: 4m

  success_criteria:
    # Critical: Network survives CPU starvation
    - name: network_survives_cpu_starvation
      description: Block production continues despite CPU throttling
      type: prometheus
      query: increase(chain_head_block{job=~"l2-el-.*-bor-heimdall-v2-validator"}[1m])
      threshold: "> 0"
      window: 8m
      critical: true

    # Critical: Consensus survives CPU starvation
    - name: consensus_survives_cpu_starvation
      description: Consensus continues despite CPU throttling
      type: prometheus
      query: increase(cometbft_consensus_height{job=~"l2-cl-.*-heimdall-v2-bor-validator"}[1m])
      threshold: "> 0"
      window: 8m
      critical: true

    # Expected: CPU-starved validator shows degraded performance
    - name: cpu_starved_validator_degrades
      description: CPU-throttled validator shows reduced consensus participation
      type: prometheus
      query: increase(cometbft_consensus_height{job="l2-cl-3-heimdall-v2-bor-validator"}[2m])
      threshold: "< 80"
      window: 8m
      critical: false

    # Expected: Other validators compensate
    - name: healthy_validators_compensate
      description: Validators 1,2,4 maintain normal performance
      type: prometheus
      query: increase(cometbft_consensus_height{job=~"l2-cl-[124]-heimdall-v2-bor-validator"}[1m])
      threshold: "> 40"
      window: 8m
      critical: false

  metrics:
    - chain_head_block
    - cometbft_consensus_height
    - process_cpu_seconds_total
    - go_goroutines
    - up
