apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: quick-cleanup-test
  description: Quick test to verify cleanup works
  tags: [test, quick]
  author: DevTools
  version: "0.0.1"

spec:
  # Target a validator node
  targets:
    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-cl-1-heimdall-v2-bor-validator"
      alias: test_validator

  # Short durations for quick test
  duration: 1m
  warmup: 10s
  cooldown: 10s

  # Simple fault: 50% packet loss
  faults:
    - phase: test_fault
      description: Test 50% packet loss
      target: test_validator
      type: network
      params:
        device: eth0
        packet_loss: 50
        target_ports: "26656,26657"
        target_proto: tcp,udp

  # No success criteria for quick test
  success_criteria: []

  # No metrics collection for quick test
  metrics: []
