apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: split-brain-partition
  description: Create a network partition splitting validators into two groups
  tags: [network, partition, split-brain, critical-severity]
  author: DevTools
  version: "0.0.1"

spec:
  targets:
    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-cl-1-heimdall-v2-bor-validator"
      alias: partition_group_a

    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-cl-2-heimdall-v2-bor-validator"
      alias: partition_group_b

  duration: 5m
  warmup: 30s
  cooldown: 1m

  faults:
    # Partition group A from group B
    - phase: partition_a_from_b
      description: Block traffic from validator 1 to validator 2
      target: partition_group_a
      type: network
      params:
        device: eth0
        packet_loss: 100
        target_ports: "26656,26657"
        target_proto: tcp,udp
        # Note: In production, you'd specify target IPs/CIDR

    # Partition group B from group A (bidirectional)
    - phase: partition_b_from_a
      description: Block traffic from validator 2 to validator 1
      target: partition_group_b
      type: network
      params:
        device: eth0
        packet_loss: 100
        target_ports: "26656,26657"
        target_proto: tcp,udp

  success_criteria:
    # Critical: Network must continue with majority
    - name: network_survives_partition
      description: Network with majority continues block production
      type: prometheus
      query: increase(chain_head_block{job=~"l2-el-.*-bor-heimdall-v2-validator"}[1m])
      threshold: "> 0"
      window: 5m
      critical: true

    # Critical: Consensus continues
    - name: consensus_continues
      description: Heimdall consensus progresses with majority
      type: prometheus
      query: increase(cometbft_consensus_height{job=~"l2-cl-.*-heimdall-v2-bor-validator"}[1m])
      threshold: "> 0"
      window: 5m
      critical: true

    # Non-critical: Checkpoint API remains accessible
    - name: checkpoint_api_accessible
      description: Checkpoint API continues to respond
      type: prometheus
      query: increase(heimdallv2_checkpoint_api_calls_total[2m])
      threshold: ">= 0"
      window: 5m
      critical: false

  metrics:
    - chain_head_block
    - cometbft_consensus_height
    - cometbft_consensus_validators
    - heimdallv2_checkpoint_api_calls_total
