apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: op-batcher-crash-during-submission
  description: Kill OP batcher during active batch submission to test transaction
    recovery
  tags:
  - failure
  - crash
  - critical
  - op-stack
  - batcher
  author: DevTools
  version: 0.0.1
spec:
  targets:
  - selector:
      type: kurtosis_service
      enclave: ${ENCLAVE_NAME}
      pattern: op-batcher.*
    alias: op_batcher
  duration: 5m
  warmup: 1m
  cooldown: 2m
  faults:
  - phase: kill_batcher
    description: Kill OP batcher during batch submission
    target: op_batcher
    type: container_kill
    params:
      signal: SIGKILL
  success_criteria:
  - name: sequencer_unaffected
    description: Sequencer continues producing blocks
    type: prometheus
    query: increase(panoptichain_rpc_height{job=~"op-el-1.*"}[1m])
    threshold: '> 0'
    window: 5m
    critical: true
  - name: batches_resume_submission
    description: Batch submissions resume after recovery
    type: prometheus
    query: increase(panoptichain_rpc_height[2m])
    threshold: '> 0'
    window: 2m
    critical: false
  metrics:
  - panoptichain_rpc_height
  - up
