apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: postgres-disk-io-saturation
  description: Saturate PostgreSQL disk I/O to test database performance under stress
  tags:
  - resource
  - disk-io
  - critical
  - database
  - postgres
  author: DevTools
  version: 0.0.1
spec:
  targets:
  - selector:
      type: kurtosis_service
      enclave: ${ENCLAVE_NAME}
      pattern: postgres.*
    alias: postgres_db
  duration: 6m
  warmup: 1m
  cooldown: 1m
  faults:
  - phase: disk_io_stress_postgres
    description: Saturate disk I/O on PostgreSQL data directory
    target: postgres_db
    type: disk_io_stress
    params:
      workers: 4
      block_size: 4096
  success_criteria:
  - name: services_continue_operating
    description: Services using database continue operating
    type: prometheus
    query: increase(panoptichain_rpc_height[1m])
    threshold: '> 0'
    window: 6m
    critical: true
  - name: services_maintain_functionality
    description: Services maintain basic functionality despite slow database
    type: prometheus
    query: increase(panoptichain_rpc_gas_used_sum[2m])
    threshold: '> 0'
    window: 6m
    critical: false
  metrics:
  - up
  - panoptichain_rpc_height
  - panoptichain_rpc_gas_used_sum
