apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: rolling-validator-restart
  description: Validators restart one-by-one with delay - proper upgrade procedure
  tags: [restart, upgrade, rolling-update, best-practice]
  author: DevTools
  version: "0.0.1"

spec:
  targets:
    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-cl-1-heimdall-v2-bor-validator"
      alias: validator1_heimdall

    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-el-1-bor-heimdall-v2-validator"
      alias: validator1_bor

    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-cl-2-heimdall-v2-bor-validator"
      alias: validator2_heimdall

    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-el-2-bor-heimdall-v2-validator"
      alias: validator2_bor

    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-cl-3-heimdall-v2-bor-validator"
      alias: validator3_heimdall

    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-el-3-bor-heimdall-v2-validator"
      alias: validator3_bor

    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-cl-4-heimdall-v2-bor-validator"
      alias: validator4_heimdall

    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-el-4-bor-heimdall-v2-validator"
      alias: validator4_bor

  duration: 12m
  warmup: 2m
  cooldown: 2m

  # Rolling restart: 2 minutes between each validator restart
  faults:
    # Validator 1 restart at 0m
    - phase: restart_validator1_heimdall
      target: validator1_heimdall
      type: container_restart
      params:
        grace_period: 10
      delay: 0m

    - phase: restart_validator1_bor
      target: validator1_bor
      type: container_restart
      params:
        grace_period: 10
      delay: 0m

    # Validator 2 restart at 3m
    - phase: restart_validator2_heimdall
      target: validator2_heimdall
      type: container_restart
      params:
        grace_period: 10
      delay: 3m

    - phase: restart_validator2_bor
      target: validator2_bor
      type: container_restart
      params:
        grace_period: 10
      delay: 3m

    # Validator 3 restart at 6m
    - phase: restart_validator3_heimdall
      target: validator3_heimdall
      type: container_restart
      params:
        grace_period: 10
      delay: 6m

    - phase: restart_validator3_bor
      target: validator3_bor
      type: container_restart
      params:
        grace_period: 10
      delay: 6m

    # Validator 4 restart at 9m
    - phase: restart_validator4_heimdall
      target: validator4_heimdall
      type: container_restart
      params:
        grace_period: 10
      delay: 9m

    - phase: restart_validator4_bor
      target: validator4_bor
      type: container_restart
      params:
        grace_period: 10
      delay: 9m

  success_criteria:
    # Critical: Block production never stops
    - name: continuous_block_production
      description: Block production continues throughout rolling restart
      type: prometheus
      query: increase(chain_head_block{job=~"l2-el-.*-bor-heimdall-v2-validator"}[1m])
      threshold: "> 0"
      window: 12m
      critical: true

    # Critical: Consensus never halts
    - name: continuous_consensus
      description: Consensus continues throughout rolling restart
      type: prometheus
      query: increase(cometbft_consensus_height{job=~"l2-cl-.*-heimdall-v2-bor-validator"}[1m])
      threshold: "> 0"
      window: 12m
      critical: true

    # Critical: At least 3 validators always active (maintains 75% > 67% threshold)
    - name: quorum_maintained
      description: At least 3 validators active at all times
      type: prometheus
      query: count(up{job=~"l2-cl-.*-heimdall-v2-bor-validator"} == 1)
      threshold: ">= 3"
      window: 12m
      critical: true

  metrics:
    - chain_head_block
    - cometbft_consensus_height
    - cometbft_consensus_validators
    - up
