apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: rolling-validator-restart
  description: Validators restart one-by-one with delay - proper upgrade procedure
  tags: [restart, upgrade, rolling-update, best-practice]
  author: DevTools
  version: "0.0.1"

spec:
  targets:
    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-cl-1-heimdall-v2-bor-validator"
      alias: validator1_heimdall

    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-el-1-bor-heimdall-v2-validator"
      alias: validator1_bor

    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-cl-2-heimdall-v2-bor-validator"
      alias: validator2_heimdall

    - selector:
        type: kurtosis_service
        enclave: "${ENCLAVE_NAME}"
        pattern: "l2-el-2-bor-heimdall-v2-validator"
      alias: validator2_bor

  # NOTE: Validators 3+ are optional; if absent the scenario still runs
  # with the validators that exist. BFT quorum requires >=3 validators
  # for block production to continue during a rolling restart.
  duration: 6m
  warmup: 2m
  cooldown: 2m

  # Rolling restart: 2 minutes between each validator restart
  faults:
    # Validator 1 restart at 0m
    - phase: restart_validator1_heimdall
      target: validator1_heimdall
      type: container_restart
      params:
        grace_period: 10
      delay: 0m

    - phase: restart_validator1_bor
      target: validator1_bor
      type: container_restart
      params:
        grace_period: 10
      delay: 0m

    # Validator 2 restart at 3m
    - phase: restart_validator2_heimdall
      target: validator2_heimdall
      type: container_restart
      params:
        grace_period: 10
      delay: 3m

    - phase: restart_validator2_bor
      target: validator2_bor
      type: container_restart
      params:
        grace_period: 10
      delay: 3m

  success_criteria:
    # Critical: Block production never stops
    - name: continuous_block_production
      description: Block production continues throughout rolling restart
      type: prometheus
      query: increase(chain_head_block{job=~"l2-el-.*-bor-heimdall-v2-validator"}[1m])
      threshold: "> 0"
      window: 6m
      critical: true

    # Critical: Consensus never halts
    - name: continuous_consensus
      description: Consensus continues throughout rolling restart
      type: prometheus
      query: increase(cometbft_consensus_height{job=~"l2-cl-.*-heimdall-v2-bor-validator"}[1m])
      threshold: "> 0"
      window: 6m
      critical: true

    # Critical: At least 2/3 of validators always active (maintains BFT quorum threshold)
    - name: quorum_maintained
      description: At least 2/3 of validators active at all times (topology-safe ratio check)
      type: prometheus
      query: count(up{job=~"l2-cl-.*-heimdall-v2-bor-validator"} == 1) / scalar(count(up{job=~"l2-cl-.*-heimdall-v2-bor-validator"}))
      threshold: ">= 0.67"
      window: 6m
      critical: true

  metrics:
    - chain_head_block
    - cometbft_consensus_height
    - cometbft_consensus_validators
    - up
