apiVersion: chaos.polygon.io/v1
kind: ChaosScenario
metadata:
  name: bridge-packet-loss
  description: Inject 20% packet loss on bridge service to test message reliability
  tags:
  - network
  - packet-loss
  - medium
  - bridge
  - l1-l2
  author: DevTools
  version: 0.0.1
spec:
  targets:
  - selector:
      type: kurtosis_service
      enclave: ${ENCLAVE_NAME}
      pattern: .*bridge.*|zkevm-bridge-service
    alias: bridge_node
  duration: 5m
  warmup: 30s
  cooldown: 30s
  faults:
  - phase: bridge_packet_loss
    description: Inject 20% packet loss on bridge service network
    target: bridge_node
    type: network
    params:
      device: eth0
      packet_loss: 20
      target_proto: tcp,udp
  success_criteria:
  - name: bridge_deposits_continue
    description: Bridge deposits continue being processed despite packet loss
    type: prometheus
    query: increase(panoptichain_rpc_bridge_deposit_count[1m])
    threshold: '> 0'
    window: 5m
    critical: true
  - name: bridge_withdrawals_continue
    description: Bridge withdrawals continue being processed
    type: prometheus
    query: increase(panoptichain_rpc_bridge_event_deposit_count[1m])
    threshold: '> 0'
    window: 5m
    critical: true
  - name: block_time_stable
    description: Block time remains stable (not increasing significantly)
    type: prometheus
    query: rate(panoptichain_rpc_block_interval_sum[2m]) / rate(panoptichain_rpc_block_interval_count[2m])
    threshold: < 5.0
    window: 5m
    critical: false
  - name: transaction_throughput_maintained
    description: Transaction processing rate doesn't drop significantly
    type: prometheus
    query: rate(panoptichain_rpc_gas_used_count[1m])
    threshold: '> 0.1'
    window: 5m
    critical: false
  - name: bridge_claims_processed
    description: Bridge claims are processed (may be delayed)
    type: prometheus
    query: increase(panoptichain_rpc_bridge_deposit_count[5m])
    threshold: '> 0'
    window: 5m
    critical: false
  - name: bridge_events_recent
    description: Bridge events are recent (< 5 minutes old)
    type: prometheus
    query: panoptichain_rpc_time_since_last_bridge_event
    threshold: < 300
    window: 5m
    critical: false
  - name: global_exit_root_synchronized
    description: L1-L2 coordination continues (global exit root updates)
    type: prometheus
    query: panoptichain_rpc_time_since_last_global_exit_root
    threshold: < 180
    window: 5m
    critical: false
  metrics:
  - panoptichain_rpc_bridge_deposit_count
  - panoptichain_rpc_bridge_event_deposit_count
  - up
  - panoptichain_rpc_block_interval_sum
  - panoptichain_rpc_block_interval_count
  - panoptichain_rpc_gas_used_count
  - panoptichain_rpc_finalized_height
  - panoptichain_rpc_time_to_finalized
  - panoptichain_rpc_time_to_mine_sum
  - panoptichain_rpc_time_to_mine_count
  - panoptichain_rpc_time_since_last_bridge_event
  - panoptichain_rpc_bridge_event_amount_sum
  - panoptichain_rpc_bridge_event_amount_count
  - panoptichain_rpc_time_since_last_global_exit_root
  - panoptichain_rpc_global_exit_roots
